version: '3'
services:
  app:
    container_name: app_spring-mvc-demo
    build: .
    ports:
      - "8082:8080"
    volumes:
      - ./env/docker/:/config
    environment:
      SPRING_CONFIG_LOCATION: /config/
    networks:
      - local-network
    depends_on:
      - db
      - mailhog

  mailhog:
    container_name: app_mailhog
    image: "mailhog/mailhog"
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      local-network:
        aliases:
          - app-mailhog

  db:
    container_name: app_mysql
    image: "mysql:5"
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: my-root-pw
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: test
    networks:
      local-network:
        aliases:
          - app-mysql

networks:
  local-network:
    driver: bridge