apiVersion: v1
kind: Service
metadata:
  name: mailhog-lb-service
spec:
  selector:
    app: mailhog
  ports:
    - name: "mailhog"
      port: 8025
      targetPort: 8025
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: mailhog-service
spec:
  ports:
    - port: 1025
      protocol: TCP
  selector:
    app: mailhog

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailhog-deployment
  labels:
    app: mailhog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailhog
  template:
    metadata:
      labels:
        app: mailhog
    spec:
      containers:
        - name: my-mailhog
          image: mailhog/mailhog
          ports:
            - containerPort: 8025
            - containerPort: 1025

---

apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app: mysql
spec:
  ports:
    - port: 3306
      protocol: TCP
  selector:
    app: mysql

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: my-mysql
          image: mysql:5
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: init-db-volume
              mountPath: /docker-entrypoint-initdb.d
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "my-root-pw"
            - name: MYSQL_DATABASE
              value: "app"
            - name: MYSQL_USER
              value: "app"
            - name: MYSQL_PASSWORD
              value: "test"
      volumes:
        - name: init-db-volume
          configMap:
            name: init-db

---

apiVersion: v1
kind: Service
metadata:
  name: spring-app-service
spec:
  selector:
    app: spring-demo
  ports:
    - name: "app"
      port: 8080
      targetPort: 8080
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app-deployment
  labels:
    app: spring-demo
spec:
  replicas: 2
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: spring-demo
  template:
    metadata:
      labels:
        app: spring-demo
    spec:
#      initContainers:
#        - name: init-db
#          image: busybox:1.28
#          command: ['sh', '-c', 'until nslookup mydb; do echo waiting for mydb; sleep 3; done;']
      containers:
      - name: app-spring-mvc-demo
        image: spring-mvc-demo:latest
        ports:
          - containerPort: 8080
        volumeMounts:
          - name: spring-config-volume
            mountPath: /config/
        env:
          - name: SPRING_CONFIG_LOCATION
            value: "/config/"
      volumes:
        - name: spring-config-volume
          configMap:
            name: spring-config