CREATE TABLE users
(
   ID INT,
   FIRST_NAME VARCHAR(50) NOT NULL,
   LAST_NAME VARCHAR(50) NOT NULL,
   ENCRYPTED_PASSWORD VARCHAR(128) NOT NULL,
   EMAIL VARCHAR(100) NOT NULL,
   GENDER VARCHAR(10),
   ENABLED INT NOT NULL,
   DOB DATE,
   PRIMARY KEY (ID)
) ;

CREATE TABLE roles
(
   ID INT NOT NULL,
   ROLE VARCHAR(30) NOT NULL,
   PRIMARY KEY (ID)
) ;

CREATE TABLE users_roles
(
   USER_ID INT NOT NULL,
   ROLE_ID INT NOT NULL,
   FOREIGN KEY (USER_ID) REFERENCES users (ID),
   FOREIGN KEY (ROLE_ID) REFERENCES roles (ID)
);

CREATE TABLE id_gen
(
   GEN_NAME VARCHAR(80),
   GEN_VAL INT,
   PRIMARY KEY (GEN_NAME)
);

CREATE TABLE verification_tokens
(
   ID INT NOT NULL,
   TOKEN VARCHAR(250) NOT NULL,
   USER_ID INT NOT NULL,
   EXPIRY_DATE TIMESTAMP,
   FOREIGN KEY (USER_ID) REFERENCES users (ID),
   PRIMARY KEY (ID)
);

INSERT INTO id_gen (GEN_NAME, GEN_VAL) VALUES ('userId', 0);
INSERT INTO id_gen (GEN_NAME, GEN_VAL) VALUES ('roleId', 2);
INSERT INTO id_gen (GEN_NAME, GEN_VAL) VALUES ('tokenId', 0);

INSERT INTO roles (ID, ROLE) VALUES (1, 'ROLE_ADMIN');
INSERT INTO roles (ID, ROLE) VALUES (2, 'ROLE_USER');